spring:
 datasource:
    url: jdbc:mysql://zohar.space:3306/block_chain
    username: $username
    password: $password
    driver-class-name: com.mysql.jdbc.Driver

# An infura endpoint
web3j:
  client-address: https://rinkeby.infura.io/O4wOvkxbqX2lj2CcwQNu
  admin-client: true

server:
    port: 8080

debug: true
logging:
  level:
    org.web3j.spring.autoconfigure: debug